global:
  scrape_interval: 5s  # cada 5 segundos

scrape_configs:
  - job_name: "fastapi-backend"
    static_configs:
      - targets: ["web-iii-calculadora-1:8000"]  # nombre del servicio y puerto dentro del network

