server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Configuraci√≥n para recolectar logs de contenedores Docker
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Etiqueta con el nombre del contenedor
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      # Etiqueta con el nombre de la imagen
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
      # Etiqueta con las labels del contenedor
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
